# CLIProxyAPI 配置文件示例 - 包含 Gemini CLI 镜像节点配置
# CLIProxyAPI Configuration Example - With Gemini CLI Mirror Nodes

# 服务器端口
port: 8080
# 认证文件目录
auth-dir: "./auths"
# 调试模式
debug: true
# 日志记录到文件
logging-to-file: true
# 使用统计启用
usage-statistics-enabled: true
# 全局代理配置（可选）
proxy-url: "socks5://127.0.0.1:10808"
# API 密钥配置
api-keys:
  - "your-api-key-here"
# Gemini CLI 镜像节点配置
gemini-cli:
  # Code Assist API 端点（必配）
  code-assist-endpoint: "https://gcli-api.sukaka.top/cloudcode-pa"
  # OAuth2 认证端点（必配）
  oauth-endpoint: "https://gcli-api.sukaka.top/oauth2"
  # Google APIs 基础端点（必配）
  google-apis-endpoint: "https://gcli-api.sukaka.top/googleapis"
  # Resource Manager API 端点（可选）
  resource-manager-endpoint: "https://gcli-api.sukaka.top/cloudresourcemanager"
  # Service Usage API 端点（可选）
  service-usage-endpoint: "https://gcli-api.sukaka.top/serviceusage"
  # Gemini CLI 专用代理（可选，覆盖全局设置）
  # proxy-url: "socks5://127.0.0.1:10808"
# Gemini Web 配置
gemini-web:
  context: true
  code-mode: true
  max-chars-per-request: 1000000
  disable-continuation-hint: false
# Claude API 配置（可选）
claude-api-key:
  - api-key: "your-claude-api-key"
    base-url: "https://api.anthropic.com"
# OpenAI 兼容配置（可选）
openai-compatibility:
  - name: "openai"
    base-url: "https://api.openai.com"
    api-key-entries:
      - api-key: "your-openai-api-key"
    models:
      - name: "gpt-4"
        alias: "gpt-4"
      - name: "gpt-3.5-turbo"
        alias: "gpt-3.5-turbo"
# 请求重试次数
request-retry: 3
# 配额超出处理
quota-exceeded:
  switch-project: true
  switch-preview-model: true
# 远程管理配置（可选）
remote-management:
  allow-remote: false
  secret-key: "$2a$10$FIQTOTAQysgyxQh0/1Nn9eMXqRm613OXsc8qiLvyccpqh9JNrunAe"
  disable-control-panel: false
