services:
  cli-proxy-api:
    image: cli-proxy-api:latest
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: v1-dev
        COMMIT: gdtiti
    container_name: cli-proxy-api
    ports:
      - "8317:8317"
      - "8085:8085"
      - "1455:1455"
      - "54545:54545"
      - "11451:11451"
    volumes:
      - ./config.yaml:/CLIProxyAPI/config.yaml
      - ./auths:/root/.cli-proxy-api
      - ./logs:/CLIProxyAPI/logs
      - ./conv:/CLIProxyAPI/conv
      - ./static:/CLIProxyAPI/static
    restart: unless-stopped
